// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6OsYtMbDcdGEeeIwd4jJkBQnNi5ilTG8',
    appId: '1:928257834650:web:2f1c0cea0e5964887d2923',
    messagingSenderId: '928257834650',
    projectId: 'kigali-1b202',
    authDomain: 'kigali-1b202.firebaseapp.com',
    storageBucket: 'kigali-1b202.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvkKjZqYAbZ1LLnRSlmNuKFAVOexVCx4',
    appId: '1:928257834650:android:9173ffe69a4781807d2923',
    messagingSenderId: '928257834650',
    projectId: 'kigali-1b202',
    storageBucket: 'kigali-1b202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yE26-FoNFhc2IM9i_n6bfi76kPMZlVE',
    appId: '1:928257834650:ios:958ddc88acd6c0547d2923',
    messagingSenderId: '928257834650',
    projectId: 'kigali-1b202',
    storageBucket: 'kigali-1b202.firebasestorage.app',
    iosBundleId: 'com.example.kigali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yE26-FoNFhc2IM9i_n6bfi76kPMZlVE',
    appId: '1:928257834650:ios:958ddc88acd6c0547d2923',
    messagingSenderId: '928257834650',
    projectId: 'kigali-1b202',
    storageBucket: 'kigali-1b202.firebasestorage.app',
    iosBundleId: 'com.example.kigali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6OsYtMbDcdGEeeIwd4jJkBQnNi5ilTG8',
    appId: '1:928257834650:web:f0cafa76113a19c77d2923',
    messagingSenderId: '928257834650',
    projectId: 'kigali-1b202',
    authDomain: 'kigali-1b202.firebaseapp.com',
    storageBucket: 'kigali-1b202.firebasestorage.app',
  );

}